version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pulsedelivery-postgres
    environment:
      POSTGRES_DB: pulsedelivery
      POSTGRES_USER: pd_user
      POSTGRES_PASSWORD: wolf
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulsedelivery-net

volumes:
  postgres_data:

networks:
  pulsedelivery-net: